# Generated by Django 2.1.7 on 2019-03-09 07:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bazaar', '0002_auto_20190309_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleproduct',
            name='date_available',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
