# Generated by Django 2.1.7 on 2019-03-11 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazaar', '0004_saleproduct_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleproduct',
            name='buyer',
            field=models.CharField(default='', max_length=150),
        ),
    ]
